# Generated by Django 4.2.20 on 2025-04-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], unique=True)),
                ('open_time', models.TimeField(help_text='Time when the shop opens')),
                ('close_time', models.TimeField(help_text='Time when the shop closes')),
            ],
        ),
    ]
