# Generated by Django 4.2.20 on 2025-04-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0004_openinghours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openinghours',
            options={'verbose_name': 'Opening Hour'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='booking',
            name='timeslots',
            field=models.ManyToManyField(related_name='bookings', to='barber.timeslot'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.DurationField(help_text='Service duration as timedelta'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('booked', 'Booked'), ('expired', 'Expired')], default='available', max_length=10),
        ),
    ]
