# Generated by Django 4.2.20 on 2025-04-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0005_alter_openinghours_options_remove_booking_time_slot_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('date', 'start_time', 'end_time')},
        ),
    ]
